language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

install:
  - pip install codecov
  - pip install -r requirements2.txt

script: coverage run -m unittest -v

after_success:
  - codecov
